export 'appointments/appointments_screen.dart';
export 'clinics/clinic_details_screen.dart';
export 'clinics/clinics_screen.dart';
export 'dashboard/dashboard_screen.dart';
export 'onboarding/onboarding_screen.dart';
export 'patients/patient_case_sheet_screen.dart';
export 'patients/patients_screen.dart';
export 'profile/profile_screen.dart';
export 'root_navigation_screen.dart';
